# Copyright (C) 2017 NVIDIA Corporation.  All rights reserved.
# Licensed under the CC BY-NC-SA 4.0 license (https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode).

# logger options

# parser.add_argument('--config', type=str, help="net configuration")
# parser.add_argument('--input', type=str, help="input image path")
# parser.add_argument('--output_folder', type=str, help="output image path")
# parser.add_argument('--checkpoint', type=str, help="checkpoint of autoencoders")
# parser.add_argument('--style', type=str, default='', help="style image path")
# parser.add_argument('--a2b', type=int, default=1, help="1 for a2b and 0 for b2a")
# parser.add_argument('--seed', type=int, default=10, help="random seed")
# parser.add_argument('--num_style',type=int, default=10, help="number of styles to sample")
# parser.add_argument('--synchronized', action='store_true', help="whether use synchronized style code or not")
# parser.add_argument('--output_only', action='store_true', help="whether use synchronized style code or not")
# parser.add_argument('--output_path', type=str, default='.', help="path for logs, checkpoints, and VGG model weight")
# parser.add_argument('--trainer', type=str, default='MUNIT', help="MUNIT|UNIT")

input:  '/home/haneollee/myworkspace/datasets/cat2dog'
# output_folder:
checkpoint:
style: ''
a2b: 1
seed: 10
num_style: 2
synchronized: 
output_only: 
output_path: '.' 
trainer: MUNIT